import smtplib
import logging
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

from jinja2 import Template

from src.alerting.engine import Alert

logger = logging.getLogger(__name__)

ALERT_EMAIL_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: Arial, sans-serif; margin: 0; padding: 20px; }
        .alert-box {
            border-left: 4px solid {{ color }};
            background: #f9f9f9;
            padding: 15px;
            margin: 10px 0;
        }
        .severity { color: {{ color }}; font-weight: bold; text-transform: uppercase; }
        .metric { font-size: 24px; font-weight: bold; }
        .details { color: #666; margin-top: 10px; }
        table { border-collapse: collapse; width: 100%; margin-top: 15px; }
        td, th { padding: 8px 12px; text-align: left; border-bottom: 1px solid #ddd; }
        th { background: #f0f0f0; }
    </style>
</head>
<body>
    <h2>Cloud Monitor Alert</h2>
    <div class="alert-box">
        <span class="severity">{{ alert.severity }}</span>
        <p class="metric">{{ alert.metric }}: {{ alert.value }}%</p>
        <p>Threshold: {{ alert.threshold }}%</p>
    </div>
    <table>
        <tr><th>Host</th><td>{{ alert.hostname }}</td></tr>
        <tr><th>Metric</th><td>{{ alert.metric }}</td></tr>
        <tr><th>Value</th><td>{{ alert.value }}%</td></tr>
        <tr><th>Threshold</th><td>{{ alert.threshold }}%</td></tr>
        <tr><th>Severity</th><td>{{ alert.severity }}</td></tr>
        <tr><th>Time</th><td>{{ timestamp }}</td></tr>
    </table>
    <p class="details">
        This alert was generated by Cloud Monitor.
        The metric will not re-alert for this host until the cooldown period expires.
    </p>
</body>
</html>
"""


class EmailNotifier:

    def __init__(
        self,
        smtp_host: str,
        smtp_port: int,
        username: str,
        password: str,
        sender: str,
        recipients: list[str],
        use_tls: bool = True,
    ):
        self.smtp_host = smtp_host
        self.smtp_port = smtp_port
        self.username = username
        self.password = password
        self.sender = sender
        self.recipients = recipients
        self.use_tls = use_tls
        self._template = Template(ALERT_EMAIL_TEMPLATE)

    def _severity_color(self, severity: str) -> str:
        return {"critical": "#dc3545", "warning": "#ffc107"}.get(
            severity, "#6c757d"
        )

    def _render_email(self, alert: Alert) -> str:
        return self._template.render(
            alert=alert,
            color=self._severity_color(alert.severity),
            timestamp=datetime.fromtimestamp(alert.timestamp).strftime(
                "%Y-%m-%d %H:%M:%S UTC"
            ),
        )

    def send(self, alert: Alert) -> bool:
        subject = (
            f"[{alert.severity.upper()}] {alert.metric} alert "
            f"on {alert.hostname}"
        )

        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = self.sender
        msg["To"] = ", ".join(self.recipients)

        html_body = self._render_email(alert)
        msg.attach(MIMEText(html_body, "html"))

        try:
            if self.use_tls:
                server = smtplib.SMTP(self.smtp_host, self.smtp_port)
                server.starttls()
            else:
                server = smtplib.SMTP_SSL(self.smtp_host, self.smtp_port)

            server.login(self.username, self.password)
            server.sendmail(self.sender, self.recipients, msg.as_string())
            server.quit()

            logger.info(f"Alert email sent: {subject}")
            return True
        except smtplib.SMTPException as e:
            logger.error(f"Failed to send alert email: {e}")
            return False
